### ISSUE TITLE
Typo in comment on PlacementSubject?

### ISSUE THREAD

**Issue by MikeSpreitzer** [stolostron/governance-policy-propagator#177]
The comment at https://github.com/stolostron/governance-policy-propagator/blob/89fa131f4cb0d87559393a841e3b05de3342e3fe/api/v1/placementbinding_types.go#L25 is a bit puzzling.  Was "Placement reference" intended instead?  Also: if it is semantically a reference to a placement, why is the word "subject" in the type's name?

**Comment by ycao56** [comment]
@MikeSpreitzer This is an oversight in the source cod comment. We will fix it. Thanks for bring it to our attention.
